version: "3.9"
services: 
    db: 
        container_name: sql_server_db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - "1433:1433"
        environment: 
            SA_PASSWORD: "Qwerty@123"
            ACCEPT_EULA: "Y"